import "dotenv/config";

const CLOUDINARY_SECURE = process.env.CLOUDINARY_SECURE || true;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY || "";
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME || "";
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET || "";
const CLOUDINARY_OUTPUT_DIRECTORY =
  process.env.CLOUDINARY_OUTPUT_DIRECTORY || "notification_service_core";

export {
  CLOUDINARY_SECURE,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_OUTPUT_DIRECTORY,
};
